import Image from "next/image";
import Link from "next/link";
import {notFound} from "next/navigation";
import type {Metadata} from "next";
import {getAgencyRoster,heroArtists} from "@/lib/agency/roster";
import {getRequestLocale} from "@/lib/i18n/server";
import styles from "../../agency.module.css";
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const a=(await getAgencyRoster()).find(a=>a.id===id);return {title:a?`${a.name} — Bright Ears` : "Artist — Bright Ears",description:a?.bio.slice(0,155)};}
export default async function ArtistPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const roster=await getAgencyRoster();const artist=roster.find(a=>a.id===id);if(!artist){if(!roster.length)return <div className={styles.accountPage}><h1>Artist profiles are temporarily unavailable.</h1><Link href="/artists">Back to the roster ↗</Link></div>;notFound();}
 const th=(await getRequestLocale())==="th";const c=(en:string,thai:string)=>th?thai:en;const hero=heroArtists.find(a=>a.id===id);const photo=hero?.image||artist.image;
 const related=roster.filter(a=>a.id!==id&&a.genres.some(g=>artist.genres.includes(g))).slice(0,4);
 return <div className={styles.profilePage}><Link href="/artists" className={styles.backLink}>← {c("The full roster","ดีเจทั้งหมด")}</Link><section className={styles.profileHero}><div className={styles.profileImage}>{photo?<Image src={photo} alt={artist.name} fill sizes="(max-width: 750px) 88vw, 45vw" preload unoptimized={photo.startsWith("https:")} style={{objectPosition:hero?.position||"50% 40%"}}/>:<span className={styles.artistPlaceholder}>{artist.name.slice(0,2)}</span>}<span className={styles.profileStamp}>BRIGHT EARS / SELECTOR</span></div><div className={styles.profileCopy}><p className={styles.kicker}>{artist.city} / DJ</p><h1>{artist.name}<span>↗</span></h1><div className={styles.genreTags}>{artist.genres.map(g=><span key={g}>{g}</span>)}</div><p className={styles.profileBio}>{(th?artist.bioTh:artist.bio)||c("Get in touch for a personal introduction, music references and availability.","ติดต่อเราเพื่อรู้จักดีเจ ฟังตัวอย่างดนตรี และสอบถามวันว่าง")}</p><Link href={`/?artists=${encodeURIComponent(id)}#brief`} className={styles.primary}>{c(`Book ${artist.name}`,`สอบถาม ${artist.name}`)} ↗</Link><p className={styles.profileNote}>{c("Tell us your date, venue and the night you have in mind. We’ll confirm availability and fees with you.","แจ้งวัน สถานที่ และบรรยากาศที่ต้องการ เราจะยืนยันวันว่างและค่าบริการกับคุณ")}</p><div className={styles.artistLinks}><p className={styles.kicker}>{c("EXPLORE THEIR WORLD","รู้จักดีเจให้มากขึ้น")}</p>{artist.links.length?artist.links.map(l=><a key={l.url} href={l.url} target="_blank" rel="noopener noreferrer">{l.label} ↗</a>):<Link href={`/?artists=${encodeURIComponent(id)}#brief`}>{c("Ask us for a mix or music reference","ขอตัวอย่างมิกซ์หรือแนวดนตรี")} ↗</Link>}</div></div></section>{related.length>0&&<section className={styles.relatedArtists}><div className={styles.editorialHeading}><h2>{c("Keep","ค้นหา")} <em>{c("listening.","ต่อไป")}</em></h2><Link href="/artists" className={styles.textLink}>{c("All artists","ดีเจทั้งหมด")} ↗</Link></div><div className={styles.relatedGrid}>{related.map(a=><Link href={"/artists/"+a.id} key={a.id}><div>{a.image&&<Image src={a.image} alt={a.name} fill sizes="(max-width: 600px) 44vw, 22vw" unoptimized={a.image.startsWith("https:")}/>}</div><h3>{a.name} ↗</h3><p>{a.genres.slice(0,2).join(" / ")}</p></Link>)}</div></section>}</div>;
}
